--
-- PostgreSQL database dump
--

-- Dumped from database version 13.2 (Debian 13.2-1.pgdg100+1)
-- Dumped by pg_dump version 13.2

-- Started on 2021-05-14 18:55:46 UTC

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 202 (class 1259 OID 17056)
-- Name: companies; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.companies (
    corp_id integer NOT NULL,
    company_name character varying(255) NOT NULL,
    web_address character varying(255) NOT NULL,
    phone_number character varying(255) NOT NULL,
    create_date date NOT NULL,
    is_approved boolean NOT NULL
);


ALTER TABLE public.companies OWNER TO postgres;

--
-- TOC entry 203 (class 1259 OID 17064)
-- Name: employees; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.employees (
    emp_id integer NOT NULL,
    first_name character varying(255) NOT NULL,
    last_name character varying(255) NOT NULL,
    job_title integer NOT NULL,
    create_date date NOT NULL,
    status boolean NOT NULL
);


ALTER TABLE public.employees OWNER TO postgres;

--
-- TOC entry 207 (class 1259 OID 17109)
-- Name: hibernate_sequence; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.hibernate_sequence
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.hibernate_sequence OWNER TO postgres;

--
-- TOC entry 201 (class 1259 OID 17048)
-- Name: individuals; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.individuals (
    ind_id integer NOT NULL,
    verification_id integer NOT NULL,
    first_name character varying(255) NOT NULL,
    last_name character varying(255) NOT NULL,
    identity_number character varying(255) NOT NULL,
    birth_date date NOT NULL,
    create_date date NOT NULL
);


ALTER TABLE public.individuals OWNER TO postgres;

--
-- TOC entry 205 (class 1259 OID 17077)
-- Name: job_positions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.job_positions (
    pos_id integer NOT NULL,
    title character varying(255) NOT NULL
);


ALTER TABLE public.job_positions OWNER TO postgres;

--
-- TOC entry 206 (class 1259 OID 17107)
-- Name: job_positions_pos_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.job_positions ALTER COLUMN pos_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.job_positions_pos_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 200 (class 1259 OID 17038)
-- Name: users; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.users (
    id integer NOT NULL,
    who_id integer NOT NULL,
    email character varying(255) NOT NULL,
    password character varying(255) NOT NULL
);


ALTER TABLE public.users OWNER TO postgres;

--
-- TOC entry 204 (class 1259 OID 17072)
-- Name: verifications; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.verifications (
    veriy_id integer NOT NULL,
    email_activation_code character varying(255) NOT NULL,
    email_expiration_date date NOT NULL,
    email_is_confirmed boolean NOT NULL,
    email_confirmed_date date NOT NULL
);


ALTER TABLE public.verifications OWNER TO postgres;

--
-- TOC entry 2980 (class 0 OID 17056)
-- Dependencies: 202
-- Data for Name: companies; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 2981 (class 0 OID 17064)
-- Dependencies: 203
-- Data for Name: employees; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 2979 (class 0 OID 17048)
-- Dependencies: 201
-- Data for Name: individuals; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 2983 (class 0 OID 17077)
-- Dependencies: 205
-- Data for Name: job_positions; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.job_positions (pos_id, title) VALUES (1, 'Software Developer');
INSERT INTO public.job_positions (pos_id, title) VALUES (2, 'Software Architect');
INSERT INTO public.job_positions (pos_id, title) VALUES (3, 'Computer Engineering');
INSERT INTO public.job_positions (pos_id, title) VALUES (4, 'IT Manager');


--
-- TOC entry 2978 (class 0 OID 17038)
-- Dependencies: 200
-- Data for Name: users; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 2982 (class 0 OID 17072)
-- Dependencies: 204
-- Data for Name: verifications; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 2991 (class 0 OID 0)
-- Dependencies: 207
-- Name: hibernate_sequence; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.hibernate_sequence', 1, false);


--
-- TOC entry 2992 (class 0 OID 0)
-- Dependencies: 206
-- Name: job_positions_pos_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.job_positions_pos_id_seq', 1, false);


--
-- TOC entry 2836 (class 2606 OID 17063)
-- Name: companies companies_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.companies
    ADD CONSTRAINT companies_pkey PRIMARY KEY (corp_id);


--
-- TOC entry 2838 (class 2606 OID 17071)
-- Name: employees employees_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.employees
    ADD CONSTRAINT employees_pkey PRIMARY KEY (emp_id);


--
-- TOC entry 2834 (class 2606 OID 17055)
-- Name: individuals individuals_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.individuals
    ADD CONSTRAINT individuals_pkey PRIMARY KEY (ind_id);


--
-- TOC entry 2842 (class 2606 OID 17081)
-- Name: job_positions job_positions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.job_positions
    ADD CONSTRAINT job_positions_pkey PRIMARY KEY (pos_id);


--
-- TOC entry 2830 (class 2606 OID 17045)
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- TOC entry 2832 (class 2606 OID 17047)
-- Name: users users_who_id_unique; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_who_id_unique UNIQUE (who_id);


--
-- TOC entry 2840 (class 2606 OID 17076)
-- Name: verifications verifications_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.verifications
    ADD CONSTRAINT verifications_pkey PRIMARY KEY (veriy_id);


--
-- TOC entry 2847 (class 2606 OID 17097)
-- Name: employees employees_job_title_foreign; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.employees
    ADD CONSTRAINT employees_job_title_foreign FOREIGN KEY (job_title) REFERENCES public.job_positions(pos_id);


--
-- TOC entry 2846 (class 2606 OID 17102)
-- Name: individuals individuals_verification_id_foreign; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.individuals
    ADD CONSTRAINT individuals_verification_id_foreign FOREIGN KEY (verification_id) REFERENCES public.verifications(veriy_id);


--
-- TOC entry 2844 (class 2606 OID 17087)
-- Name: users users_who_id_foreign_corp; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_who_id_foreign_corp FOREIGN KEY (who_id) REFERENCES public.companies(corp_id);


--
-- TOC entry 2845 (class 2606 OID 17092)
-- Name: users users_who_id_foreign_emp; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_who_id_foreign_emp FOREIGN KEY (who_id) REFERENCES public.employees(emp_id);


--
-- TOC entry 2843 (class 2606 OID 17082)
-- Name: users users_who_id_foreign_ind; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_who_id_foreign_ind FOREIGN KEY (who_id) REFERENCES public.individuals(ind_id);


-- Completed on 2021-05-14 18:55:46 UTC

--
-- PostgreSQL database dump complete
--

